services:
  db:
    image: postgres:16
    container_name: portfolio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: portfolio_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Backend CORS and API
      ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
      # Database (matches defaults in app/core/config.py)
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      # Alternatively provide DATABASE_URL directly:
      # DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
    ports:
      - "8000:8000"
    # Live-reload workflow: mount source RW and run uvicorn --reload
    volumes:
      - ./app:/app/app:rw
    command: [
      "uvicorn",
      "app.main:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload"
    ]

  adminer:
    image: adminer:4
    container_name: portfolio_adminer
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
