[project]
name = "portfolio-backend"
version = "0.0.1"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "python-multipart",
  "sqlalchemy>=2.0",
  "alembic>=1.7",
  "asyncpg",
  "pydantic>=2.0",
]
