"""fix updated_at auto-update

Revision ID: 073c06dc79b7
Revises: 6ebe1f7dcc9a
Create Date: 2025-10-15 23:32:43.488650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073c06dc79b7'
down_revision: Union[str, None] = '6ebe1f7dcc9a'
branch_labels: Union[str, Sequence[str], None] = None
  # depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
