"""add_timezone_awareness_to_datetime_columns

Revision ID: 6d40c888e256
Revises: 0adee79e99d0
Create Date: 2025-11-18 18:45:21.054488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d40c888e256'
down_revision: Union[str, None] = '0adee79e99d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('site_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_site_views_site_ts'), table_name='site_views')
    op.drop_constraint(op.f('uq_site_views_dedup'), 'site_views', type_='unique')
    op.create_index('ix_site_views_site', 'site_views', ['site_id'], unique=False)
    op.drop_column('site_views', 'ip_hash')
    op.drop_column('site_views', 'referrer')
    op.drop_column('site_views', 'viewed_on')
    op.drop_column('site_views', 'user_agent')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('site_views', sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('site_views', sa.Column('viewed_on', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
    op.add_column('site_views', sa.Column('referrer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('site_views', sa.Column('ip_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_site_views_site', table_name='site_views')
    op.create_unique_constraint(op.f('uq_site_views_dedup'), 'site_views', ['site_id', 'ip_hash', 'viewed_on'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_site_views_site_ts'), 'site_views', ['site_id', 'viewed_at'], unique=False)
    op.alter_column('site_views', 'viewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'issued_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
