"""Add resumes table

Revision ID: d1592f313169
Revises: 
Create Date: 2025-09-20 18:50:55.602187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1592f313169'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('source_file_id', sa.BigInteger(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'parsing', 'success', 'failed', name='parse_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_resumes_version_pos'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resumes_status', 'resumes', ['parse_status'], unique=False)
    op.create_index('ix_resumes_updated_at', 'resumes', ['updated_at'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index('uq_resumes_user_primary', 'resumes', ['user_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_resumes_user_primary', table_name='resumes', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index('ix_resumes_updated_at', table_name='resumes')
    op.drop_index('ix_resumes_status', table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
